const lectureSites = {
	fastcampus: 'https://fastcampus.co.kr/',
	taling: 'https://taling.me/Home/Search/?cateSub=',
	inflean: 'https://www.inflearn.com/courses/it-programming/',
}

export const lecturePages = {
	fastcampus: [
		lectureSites.fastcampus + 'category_online_programmingfront',
		lectureSites.fastcampus + 'category_online_programmingback',
		lectureSites.fastcampus + 'category_online_programmingdevops',
		lectureSites.fastcampus + 'category_online_programmingapp',
		lectureSites.fastcampus + 'category_online_programmingcareer',
		lectureSites.fastcampus + 'category_online_programmingcoding',
		lectureSites.fastcampus + 'category_online_programminggame',
		lectureSites.fastcampus + 'category_online_datasciencemr',
		lectureSites.fastcampus + 'category_online_datasciencedl',
		lectureSites.fastcampus + 'category_online_datascienceanal',
		lectureSites.fastcampus + 'category_online_datascienceeng',
		lectureSites.fastcampus + 'category_online_dgntool',
		lectureSites.fastcampus + 'category_online_dgnuxui',
		lectureSites.fastcampus + 'category_online_dgnvisual',
		lectureSites.fastcampus + 'category_online_dgnillu',
		lectureSites.fastcampus + 'category_online_videoedit',
		lectureSites.fastcampus + 'category_online_videomotion',
		lectureSites.fastcampus + 'category_online_videogame',
		lectureSites.fastcampus + 'category_online_videovfx',
		lectureSites.fastcampus + 'category_online_financerealestate',
		lectureSites.fastcampus + 'category_online_financeaccounting',
		lectureSites.fastcampus + 'category_online_financeinvest',
		lectureSites.fastcampus + 'category_online_marketingdgt',
		lectureSites.fastcampus + 'category_online_marketingsns',
		lectureSites.fastcampus + 'category_online_marketingdata',
		lectureSites.fastcampus + 'category_online_marketingwriting',
		lectureSites.fastcampus + 'category_online_bizppt',
		lectureSites.fastcampus + 'category_online_bizexcel',
		lectureSites.fastcampus + 'category_online_bizcom',
		lectureSites.fastcampus + 'category_online_bizauto',
		lectureSites.fastcampus + 'category_online_bizleadership',
		lectureSites.fastcampus + 'category_online_investstock',
		lectureSites.fastcampus + 'category_online_investrealestate',
		lectureSites.fastcampus + 'category_online_entrepreneurship',
	],
	taling: [
		lectureSites.taling + 48,
		lectureSites.taling + 206,
		lectureSites.taling + 209,
		lectureSites.taling + 276,
		lectureSites.taling + 277,
		lectureSites.taling + 278,
		lectureSites.taling + 279,
		lectureSites.taling + 280,
		lectureSites.taling + 289,
		lectureSites.taling + 290,
		lectureSites.taling + 291,
		lectureSites.taling + 292,
		lectureSites.taling + 295,
		lectureSites.taling + 296,
		lectureSites.taling + 298,
		lectureSites.taling + 299,
		lectureSites.taling + 300,
		lectureSites.taling + 301,
		lectureSites.taling + 303,
		lectureSites.taling + 306,
		lectureSites.taling + 309,
		lectureSites.taling + 310,
	],
}
